ServerEvents.tags('item', event => {
  
  // not stackable in bundles //////////////////////////////////////
  event.add('bundled:cannot_nest', 'minecraft:bow')
  event.add('bundled:cannot_nest', 'minecraft:crossbow')
  event.add('bundled:cannot_nest', 'minecraft:shield')
  event.add('bundled:cannot_nest', 'minecraft:fishing_rod')

  event.add('bundled:cannot_nest', 'minecraft:white_bed')
  event.add('bundled:cannot_nest', 'minecraft:orange_bed')
  event.add('bundled:cannot_nest', 'minecraft:magenta_bed')
  event.add('bundled:cannot_nest', 'minecraft:light_blue_bed')
  event.add('bundled:cannot_nest', 'minecraft:yellow_bed')
  event.add('bundled:cannot_nest', 'minecraft:lime_bed')
  event.add('bundled:cannot_nest', 'minecraft:pink_bed')
  event.add('bundled:cannot_nest', 'minecraft:gray_bed')
  event.add('bundled:cannot_nest', 'minecraft:light_gray_bed')
  event.add('bundled:cannot_nest', 'minecraft:cyan_bed')
  event.add('bundled:cannot_nest', 'minecraft:purple_bed')
  event.add('bundled:cannot_nest', 'minecraft:blue_bed')
  event.add('bundled:cannot_nest', 'minecraft:brown_bed')
  event.add('bundled:cannot_nest', 'minecraft:green_bed')
  event.add('bundled:cannot_nest', 'minecraft:red_bed')
  event.add('bundled:cannot_nest', 'minecraft:black_bed')

  event.add('bundled:cannot_nest', 'minecraft:golden_axe')
  event.add('bundled:cannot_nest', 'minecraft:golden_boots')
  event.add('bundled:cannot_nest', 'minecraft:golden_chestplate')
  event.add('bundled:cannot_nest', 'minecraft:golden_helmet')
  event.add('bundled:cannot_nest', 'minecraft:golden_leggings')
  event.add('bundled:cannot_nest', 'minecraft:golden_hoe')
  event.add('bundled:cannot_nest', 'minecraft:golden_pickaxe')
  event.add('bundled:cannot_nest', 'minecraft:golden_shovel')
  event.add('bundled:cannot_nest', 'minecraft:golden_sword')
  event.add('bundled:cannot_nest', 'minecraft:iron_axe')
  event.add('bundled:cannot_nest', 'minecraft:iron_boots')
  event.add('bundled:cannot_nest', 'minecraft:iron_chestplate')
  event.add('bundled:cannot_nest', 'minecraft:iron_helmet')
  event.add('bundled:cannot_nest', 'minecraft:iron_hoe')
  event.add('bundled:cannot_nest', 'minecraft:iron_leggings')
  event.add('bundled:cannot_nest', 'minecraft:iron_pickaxe')
  event.add('bundled:cannot_nest', 'minecraft:iron_shovel')
  event.add('bundled:cannot_nest', 'minecraft:iron_sword')
  event.add('bundled:cannot_nest', 'minecraft:stone_axe')
  event.add('bundled:cannot_nest', 'minecraft:stone_hoe')
  event.add('bundled:cannot_nest', 'minecraft:stone_pickaxe')
  event.add('bundled:cannot_nest', 'minecraft:stone_shovel')
  event.add('bundled:cannot_nest', 'minecraft:stone_sword')
  event.add('bundled:cannot_nest', 'minecraft:chainmail_boots')
  event.add('bundled:cannot_nest', 'minecraft:chainmail_chestplate')
  event.add('bundled:cannot_nest', 'minecraft:chainmail_helmet')
  event.add('bundled:cannot_nest', 'minecraft:chainmail_leggings')
  event.add('bundled:cannot_nest', 'minecraft:diamond_axe')
  event.add('bundled:cannot_nest', 'minecraft:diamond_boots')
  event.add('bundled:cannot_nest', 'minecraft:diamond_chestplate')
  event.add('bundled:cannot_nest', 'minecraft:diamond_helmet')
  event.add('bundled:cannot_nest', 'minecraft:diamond_hoe')
  event.add('bundled:cannot_nest', 'minecraft:diamond_leggings')
  event.add('bundled:cannot_nest', 'minecraft:diamond_pickaxe')
  event.add('bundled:cannot_nest', 'minecraft:diamond_shovel')
  event.add('bundled:cannot_nest', 'minecraft:diamond_sword')

  // 4x stackable in bundles //////////////////////////////////////
  event.add('bundled:quarter_weight', 'charm:atlas')

  // 16x stackable in bundles //////////////////////////////////////
  event.add('bundled:sixteenth_weight', 'minecraft:filled_map')
  event.add('bundled:sixteenth_weight', 'minecraft:writable_book')
  event.add('bundled:sixteenth_weight', 'minecraft:written_book')
  event.add('bundled:sixteenth_weight', 'minecraft:sweet_berries')
  event.add('bundled:sixteenth_weight', 'minecraft:melon_slice')
  event.add('bundled:sixteenth_weight', 'minecraft:glow_berries')

  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_13')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_cat')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_blocks')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_chirp')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_far')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_mall')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_mellohi')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_stal')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_strad')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_ward')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_11')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_wait')
  event.add('bundled:sixteenth_weight', 'minecraft:music_disc_pigstep')
  
  // disable amendments torch attacking setting mobs on fire
  event.removeAll('amendments:sets_on_fire')
});
